server:
  port: 8888
  

logging:
  level:
    root: DEBUG

spring:
  cloud:
    config:
      server:
        git:
          uri: /home/az/project/ms-config-repo
          
        
  application:
    name: ms-config-server

